"""Authentication for the web chat: passphrase + Telegram code + sessions
(web-chat plan track 2, design section 4).

Two factors, neither of which this module ever exposes in a log line or
an exception message:

1. **Passphrase.** `WEB_PASSPHRASE_HASH` (app/config.py) holds
   ``scrypt$17$8$1$<salt_b64>$<hash_b64>``, generated by
   scripts/web_passphrase.py. `verify_passphrase` runs the scrypt hash
   in `asyncio.to_thread` (it is deliberately expensive -- ~100ms+ --
   and must never block the event loop) and compares with
   `hmac.compare_digest`. It always performs a real scrypt computation,
   even when the configured hash is malformed or empty, precisely so a
   timing measurement cannot distinguish "wrong passphrase" from
   "web UI misconfigured" (design section 4: "Passphrase failures take
   similar time regardless of cause").

2. **Telegram code.** `CodeStore` is in-memory (module-level state would
   not survive a redeploy, and does not need to -- design section 4
   point 4: "A restart only invalidates pending codes"), keyed by the
   opaque pre-auth token issued after a correct passphrase. Only
   `sha256(code)` is ever stored; the code itself is single-use, expires
   after `WEB_LOGIN_CODE_TTL_S`, and is invalidated after 5 wrong
   verify attempts. app/web/routes.py sends the code text with the
   *real* Bot to `settings.ALLOWED_CHAT_ID` -- never the web sink, and
   never a chat id read from the request.

Sessions live in the `web_session` table (app/db/models.py): only
`sha256(token)` is stored, so a leaked row cannot be replayed as a
cookie any more than a leaked TELEGRAM_SECRET_TOKEN hash could be
replayed as the secret itself. `validate_session` enforces both the
idle timeout and the absolute ceiling at request time (the table has no
CHECK for either -- "now" is not something a CHECK constraint can read)
and throttles the `last_seen_at` write to once per 60s, so a chatty
client polling /api/me does not turn every request into a write.

`revoke_all` is the kill switch app/tg/router.py's `/weblogout` command
and (indirectly, via `web_session` being in `app/core/purge.py`'s
`PURGED_TABLES`) `/delete` both rely on: it empties `web_session` and
calls `hub.close_all()`, which the second adversarial critique's
finding 5 specifically asked for -- revoking the database rows alone
would leave an already-open browser tab's SSE stream (and its live
callback allowlist entries) untouched.
"""

from __future__ import annotations

import asyncio
import base64
import datetime
import hashlib
import hmac
import logging
import secrets

from sqlalchemy import delete
from sqlalchemy.ext.asyncio import AsyncSession

from app.config import Settings
from app.core.clock import Clock
from app.db.models import WebSession
from app.web.hub import WebHub

logger = logging.getLogger(__name__)

# Cookie names. The __Host- prefix is a browser-enforced guarantee: it
# rejects a cookie by that name unless the response also sets Secure,
# Path=/, and carries no Domain attribute -- exactly the attributes
# app/web/routes.py sets, so the browser itself refuses a
# misconfigured or downgraded cookie rather than silently accepting one.
SESSION_COOKIE = "__Host-anchor_s"
PRE_COOKIE = "__Host-anchor_pre"

# scrypt cost parameters, fixed (not read from the hash string beyond
# format-validating them): app/config.py's _PASSPHRASE_HASH_RE and
# scripts/web_passphrase.py both hardcode N=2**17/r=8/p=1, so this
# module does too rather than trusting an attacker-influenced hash
# string to name its own cost parameters.
_SCRYPT_N = 2**17
_SCRYPT_R = 8
_SCRYPT_P = 1
_SCRYPT_MAXMEM = 256 * 1024 * 1024  # 256 MiB, per scripts/web_passphrase.py

# A dummy salt/digest scrypt runs against when the configured hash is
# missing or malformed, so verify_passphrase's cost is identical either
# way (see the module docstring). Fixed, not random: this path only
# ever runs when the deploy is already misconfigured (check_runtime_
# settings refuses to boot otherwise), so there is no secret here to
# protect with randomness -- only a cost to match.
_DUMMY_SALT = b"\x00" * 16
_DUMMY_DIGEST = b"\x00" * 64

# Crockford base32: digits and uppercase letters minus I, L, O, U, which
# are easy to misread or mistype (and, for I/O, easy to confuse with
# 1/0 in a font that does not distinguish them). The login code is read
# off a phone screen and typed on a different device, so this is not
# decoration.
_CODE_ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ"
_CODE_LENGTH = 8
CODE_MAX_ATTEMPTS = 5


def _b64_decode(value: str) -> bytes:
    padding = "=" * (-len(value) % 4)
    return base64.urlsafe_b64decode(value + padding)


def parse_passphrase_hash(value: str) -> tuple[bytes, bytes] | None:
    """"scrypt$17$8$1$<salt_b64>$<hash_b64>" -> (salt, digest), or None.

    Independent of app/config.py's `_PASSPHRASE_HASH_RE` on purpose (see
    that regex's comment) -- this is the parser that actually feeds
    hashlib.scrypt, the format check is the boot-time backstop.
    """
    parts = value.split("$")
    if len(parts) != 6:
        return None
    algo, n_exp, r, p, salt_b64, digest_b64 = parts
    if algo != "scrypt" or (n_exp, r, p) != ("17", "8", "1"):
        return None
    try:
        salt = _b64_decode(salt_b64)
        digest = _b64_decode(digest_b64)
    except Exception:  # noqa: BLE001 - any decode failure means "malformed"
        return None
    if not salt or not digest:
        return None
    return salt, digest


async def verify_passphrase(passphrase: str, configured_hash: str) -> bool:
    """Constant-cost passphrase check. Always runs a real scrypt hash.

    `asyncio.to_thread` because hashlib.scrypt is a blocking, CPU-bound
    call by design (that cost is the whole point of using scrypt over
    something faster) and must not stall the event loop -- every other
    web request, and the worker's claim loop, share this process.
    """
    parsed = parse_passphrase_hash(configured_hash)
    salt, expected = parsed if parsed is not None else (_DUMMY_SALT, _DUMMY_DIGEST)
    computed = await asyncio.to_thread(
        hashlib.scrypt,
        passphrase.encode("utf-8"),
        salt=salt,
        n=_SCRYPT_N,
        r=_SCRYPT_R,
        p=_SCRYPT_P,
        maxmem=_SCRYPT_MAXMEM,
        dklen=len(expected),
    )
    if parsed is None:
        return False
    return hmac.compare_digest(computed, expected)


# --- the Telegram login code -------------------------------------------


def _normalize_code(code: str) -> str:
    """"xxxx-XXXX", "xxxxxxxx", or with surrounding whitespace -> "XXXXXXXX"."""
    return code.strip().upper().replace("-", "")


def _hash_code(normalized: str) -> bytes:
    return hashlib.sha256(normalized.encode("ascii", errors="ignore")).digest()


class _CodeEntry:
    __slots__ = ("code_hash", "expires_at", "attempts")

    def __init__(self, code_hash: bytes, expires_at: datetime.datetime) -> None:
        self.code_hash = code_hash
        self.expires_at = expires_at
        self.attempts = 0


class CodeStore:
    """In-memory one-time-code state, keyed by pre-auth token.

    Deliberately not persisted: a code is only ever meaningful within
    the few minutes of one login attempt, and a process restart during
    that window should invalidate it, not resurrect it against a code
    the user's phone no longer shows (design section 4 point 4).

    One entry per pre-auth token, replaced (never merged) by `issue` --
    resubmitting the passphrase always invalidates whatever code was
    pending before, so an old code left on a phone's lock screen stops
    working the moment a new one is requested.
    """

    def __init__(self) -> None:
        self._entries: dict[str, _CodeEntry] = {}

    def issue(self, pre_token: str, clock: Clock, ttl_s: int) -> str:
        """Mint a fresh code for `pre_token`, replacing any pending one.

        Returns the formatted "XXXX-XXXX" code to send over Telegram.
        Only its hash is kept here.
        """
        raw = "".join(secrets.choice(_CODE_ALPHABET) for _ in range(_CODE_LENGTH))
        expires_at = clock.now_utc() + datetime.timedelta(seconds=ttl_s)
        self._entries[pre_token] = _CodeEntry(_hash_code(raw), expires_at)
        return f"{raw[:4]}-{raw[4:]}"

    def pending(self, pre_token: str, clock: Clock) -> bool:
        """True iff `pre_token` names a live, unexpired, unconsumed code.

        Used by GET /api/me to answer stage="code" without consuming an
        attempt or touching the code itself.
        """
        entry = self._entries.get(pre_token)
        if entry is None:
            return False
        if clock.now_utc() >= entry.expires_at:
            del self._entries[pre_token]
            return False
        return True

    def verify(self, pre_token: str, code: str, clock: Clock) -> bool:
        """Check `code` against the pending entry for `pre_token`.

        Single-use: a correct verification removes the entry so it can
        never be replayed. Wrong verifications count against
        CODE_MAX_ATTEMPTS and, once exhausted, remove the entry too --
        "the code is invalidated", not "the attempt counter resets on
        its own TTL".
        """
        entry = self._entries.get(pre_token)
        if entry is None:
            return False
        if clock.now_utc() >= entry.expires_at:
            del self._entries[pre_token]
            return False
        entry.attempts += 1
        if hmac.compare_digest(_hash_code(_normalize_code(code)), entry.code_hash):
            del self._entries[pre_token]
            return True
        if entry.attempts >= CODE_MAX_ATTEMPTS:
            del self._entries[pre_token]
        return False

    def discard(self, pre_token: str) -> None:
        self._entries.pop(pre_token, None)

    def clear(self) -> None:
        """Drop every pending code, for every pre-auth token at once.

        The other half of the kill switch's promise: the login-code
        message itself says "Если это не ты — /weblogout" (routes.py's
        CODE_MESSAGE), but /weblogout's revoke_all used to touch only
        `web_session` -- an attacker who already has a pending code (or
        who requests a fresh one moments later) could still complete
        the login after the owner believes it was revoked. Called from
        revoke_all below.
        """
        self._entries.clear()


# --- sessions ------------------------------------------------------------


def _hash_token(token: str) -> bytes:
    """sha256 of a session-cookie token.

    `token` is attacker-controlled: it comes straight off an
    unauthenticated request's `__Host-anchor_s` cookie, and a genuine
    token (secrets.token_urlsafe(32)) is always plain ASCII -- but
    nothing stops a forged or corrupted cookie value from containing
    non-ASCII characters -- including a lone (unpaired) surrogate
    codepoint, the shape a raw header byte that was not valid UTF-8 can
    leave behind after decoding. `.encode("ascii")` used to raise
    UnicodeEncodeError on any of these, an unhandled 500 from every
    endpoint that calls validate_session/revoke_session (GET /api/me,
    /api/history, /api/send, /api/press, /api/events, POST /api/auth/
    logout) -- one that also skips app/web/security.py's header
    middleware entirely, since the exception propagates past
    `_apply_headers` (a low-severity finding: any unauthenticated
    request could trigger it). `errors="backslashreplace"` is the encode
    handler that never raises, for any `str` whatsoever (unlike
    "surrogateescape", which still raises on a lone surrogate that is
    outside its own escape range) -- a non-ASCII or otherwise
    unencodable cookie still hashes to *some* 32 bytes, just never the
    ones a real token (always ASCII) would ever produce, so
    `db.get(WebSession, ...)` simply finds no row and the caller gets
    its ordinary "not authenticated" answer.
    """
    return hashlib.sha256(token.encode("utf-8", errors="backslashreplace")).digest()


async def create_session(
    db: AsyncSession, clock: Clock, settings: Settings
) -> tuple[str, datetime.datetime]:
    """Issue a new session. Returns (raw token, expires_at).

    The raw token is returned exactly once, for the caller to set as
    the session cookie -- it is never stored or logged; only its sha256
    lives in `web_session.token_hash`.
    """
    token = secrets.token_urlsafe(32)
    now = clock.now_utc()
    expires_at = now + datetime.timedelta(days=settings.WEB_SESSION_MAX_DAYS)
    db.add(
        WebSession(
            token_hash=_hash_token(token),
            created_at=now,
            last_seen_at=now,
            expires_at=expires_at,
        )
    )
    await db.commit()
    return token, expires_at


# last_seen_at is only rewritten this often -- see validate_session.
_LAST_SEEN_THROTTLE = datetime.timedelta(seconds=60)


async def validate_session(
    db: AsyncSession, clock: Clock, settings: Settings, token: str | None
) -> bool:
    """True iff `token` names a live session: not expired, not idle-timed-out.

    Idle timeout and absolute ceiling are both computed here, at read
    time, against the current clock -- not by a stored "still valid"
    flag anything could get stale. A valid session's `last_seen_at` is
    advanced, but only once per `_LAST_SEEN_THROTTLE`, so a client
    polling GET /api/me or holding an SSE stream open does not turn
    every request into a write.
    """
    if not token:
        return False
    row = await db.get(WebSession, _hash_token(token))
    if row is None:
        return False
    now = clock.now_utc()
    if row.expires_at <= now:
        return False
    idle_cutoff = now - datetime.timedelta(hours=settings.WEB_SESSION_IDLE_HOURS)
    if row.last_seen_at <= idle_cutoff:
        return False
    if now - row.last_seen_at >= _LAST_SEEN_THROTTLE:
        row.last_seen_at = now
        await db.commit()
    return True


async def revoke_session(db: AsyncSession, token: str | None) -> None:
    """POST /api/auth/logout: end exactly this one session. A no-op for
    a missing or already-unknown token, so logging out twice, or
    logging out with no session cookie at all, is harmless.
    """
    if not token:
        return
    await db.execute(delete(WebSession).where(WebSession.token_hash == _hash_token(token)))
    await db.commit()


async def revoke_all(db: AsyncSession, hub: WebHub, code_store: CodeStore | None = None) -> None:
    """The kill switch: end every session, every live stream, and every
    pending login code.

    Called by app/tg/router.py's `/weblogout` handler. Also the reason
    `web_session` is in app/core/purge.py's PURGED_TABLES: `/delete`
    truncating that table is the database half of this same guarantee,
    though a Telegram-issued `/delete` has no WebHub to close (nothing
    in app/core/purge.py holds one) -- `/weblogout` is the one command
    that closes both halves in one call.

    `code_store` is optional (default None) only so a caller with no
    CodeStore to hand -- there is none in this module's own tests that
    predate this parameter -- still compiles; app/main.py/track 2 always
    builds one alongside the hub and threads it through build_router the
    same way, so production never calls this with None. Clearing it here
    is what makes "Если это не ты — /weblogout" (routes.py's CODE_MESSAGE)
    true: without it, a code already issued (or one requested moments
    after the kill switch) stays valid and lets the login it was meant to
    stop complete anyway.
    """
    await db.execute(delete(WebSession))
    await db.commit()
    hub.close_all()
    if code_store is not None:
        code_store.clear()
